// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mitoblockchaindev/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257a72cb45763f8, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257a72cb45763f8, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryDiscountTokensRequest struct {
	// Adding pagination to request
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDiscountTokensRequest) Reset()         { *m = QueryDiscountTokensRequest{} }
func (m *QueryDiscountTokensRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDiscountTokensRequest) ProtoMessage()    {}
func (*QueryDiscountTokensRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257a72cb45763f8, []int{2}
}
func (m *QueryDiscountTokensRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDiscountTokensRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDiscountTokensRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDiscountTokensRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDiscountTokensRequest.Merge(m, src)
}
func (m *QueryDiscountTokensRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDiscountTokensRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDiscountTokensRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDiscountTokensRequest proto.InternalMessageInfo

func (m *QueryDiscountTokensRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryDiscountTokensResponse struct {
	// Returning a list of discount tokens
	DiscountToken []*DiscountToken `protobuf:"bytes,1,rep,name=DiscountToken,proto3" json:"DiscountToken,omitempty"`
	// Adding pagination to response
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDiscountTokensResponse) Reset()         { *m = QueryDiscountTokensResponse{} }
func (m *QueryDiscountTokensResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDiscountTokensResponse) ProtoMessage()    {}
func (*QueryDiscountTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257a72cb45763f8, []int{3}
}
func (m *QueryDiscountTokensResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDiscountTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDiscountTokensResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDiscountTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDiscountTokensResponse.Merge(m, src)
}
func (m *QueryDiscountTokensResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDiscountTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDiscountTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDiscountTokensResponse proto.InternalMessageInfo

func (m *QueryDiscountTokensResponse) GetDiscountToken() []*DiscountToken {
	if m != nil {
		return m.DiscountToken
	}
	return nil
}

func (m *QueryDiscountTokensResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetDiscountTokenStatusRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetDiscountTokenStatusRequest) Reset()         { *m = QueryGetDiscountTokenStatusRequest{} }
func (m *QueryGetDiscountTokenStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDiscountTokenStatusRequest) ProtoMessage()    {}
func (*QueryGetDiscountTokenStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257a72cb45763f8, []int{4}
}
func (m *QueryGetDiscountTokenStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDiscountTokenStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDiscountTokenStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDiscountTokenStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDiscountTokenStatusRequest.Merge(m, src)
}
func (m *QueryGetDiscountTokenStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDiscountTokenStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDiscountTokenStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDiscountTokenStatusRequest proto.InternalMessageInfo

func (m *QueryGetDiscountTokenStatusRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetDiscountTokenStatusResponse struct {
	DiscountTokenStatus DiscountTokenStatus `protobuf:"bytes,1,opt,name=DiscountTokenStatus,proto3" json:"DiscountTokenStatus"`
}

func (m *QueryGetDiscountTokenStatusResponse) Reset()         { *m = QueryGetDiscountTokenStatusResponse{} }
func (m *QueryGetDiscountTokenStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDiscountTokenStatusResponse) ProtoMessage()    {}
func (*QueryGetDiscountTokenStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257a72cb45763f8, []int{5}
}
func (m *QueryGetDiscountTokenStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDiscountTokenStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDiscountTokenStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDiscountTokenStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDiscountTokenStatusResponse.Merge(m, src)
}
func (m *QueryGetDiscountTokenStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDiscountTokenStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDiscountTokenStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDiscountTokenStatusResponse proto.InternalMessageInfo

func (m *QueryGetDiscountTokenStatusResponse) GetDiscountTokenStatus() DiscountTokenStatus {
	if m != nil {
		return m.DiscountTokenStatus
	}
	return DiscountTokenStatus{}
}

type QueryAllDiscountTokenStatusRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDiscountTokenStatusRequest) Reset()         { *m = QueryAllDiscountTokenStatusRequest{} }
func (m *QueryAllDiscountTokenStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllDiscountTokenStatusRequest) ProtoMessage()    {}
func (*QueryAllDiscountTokenStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257a72cb45763f8, []int{6}
}
func (m *QueryAllDiscountTokenStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDiscountTokenStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDiscountTokenStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDiscountTokenStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDiscountTokenStatusRequest.Merge(m, src)
}
func (m *QueryAllDiscountTokenStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDiscountTokenStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDiscountTokenStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDiscountTokenStatusRequest proto.InternalMessageInfo

func (m *QueryAllDiscountTokenStatusRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllDiscountTokenStatusResponse struct {
	DiscountTokenStatus []DiscountTokenStatus `protobuf:"bytes,1,rep,name=DiscountTokenStatus,proto3" json:"DiscountTokenStatus"`
	Pagination          *query.PageResponse   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDiscountTokenStatusResponse) Reset()         { *m = QueryAllDiscountTokenStatusResponse{} }
func (m *QueryAllDiscountTokenStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllDiscountTokenStatusResponse) ProtoMessage()    {}
func (*QueryAllDiscountTokenStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257a72cb45763f8, []int{7}
}
func (m *QueryAllDiscountTokenStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDiscountTokenStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDiscountTokenStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDiscountTokenStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDiscountTokenStatusResponse.Merge(m, src)
}
func (m *QueryAllDiscountTokenStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDiscountTokenStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDiscountTokenStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDiscountTokenStatusResponse proto.InternalMessageInfo

func (m *QueryAllDiscountTokenStatusResponse) GetDiscountTokenStatus() []DiscountTokenStatus {
	if m != nil {
		return m.DiscountTokenStatus
	}
	return nil
}

func (m *QueryAllDiscountTokenStatusResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryDiscountTokenStatusQRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Adding pagination to request
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDiscountTokenStatusQRequest) Reset()         { *m = QueryDiscountTokenStatusQRequest{} }
func (m *QueryDiscountTokenStatusQRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDiscountTokenStatusQRequest) ProtoMessage()    {}
func (*QueryDiscountTokenStatusQRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257a72cb45763f8, []int{8}
}
func (m *QueryDiscountTokenStatusQRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDiscountTokenStatusQRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDiscountTokenStatusQRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDiscountTokenStatusQRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDiscountTokenStatusQRequest.Merge(m, src)
}
func (m *QueryDiscountTokenStatusQRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDiscountTokenStatusQRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDiscountTokenStatusQRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDiscountTokenStatusQRequest proto.InternalMessageInfo

func (m *QueryDiscountTokenStatusQRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *QueryDiscountTokenStatusQRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryDiscountTokenStatusQResponse struct {
	DiscountToken *DiscountToken `protobuf:"bytes,1,opt,name=DiscountToken,proto3" json:"DiscountToken,omitempty"`
	// Returning a list of discount token status
	DiscountTokenStatus []*DiscountTokenStatus `protobuf:"bytes,2,rep,name=DiscountTokenStatus,proto3" json:"DiscountTokenStatus,omitempty"`
	// Adding pagination to response
	Pagination *query.PageResponse `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDiscountTokenStatusQResponse) Reset()         { *m = QueryDiscountTokenStatusQResponse{} }
func (m *QueryDiscountTokenStatusQResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDiscountTokenStatusQResponse) ProtoMessage()    {}
func (*QueryDiscountTokenStatusQResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257a72cb45763f8, []int{9}
}
func (m *QueryDiscountTokenStatusQResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDiscountTokenStatusQResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDiscountTokenStatusQResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDiscountTokenStatusQResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDiscountTokenStatusQResponse.Merge(m, src)
}
func (m *QueryDiscountTokenStatusQResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDiscountTokenStatusQResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDiscountTokenStatusQResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDiscountTokenStatusQResponse proto.InternalMessageInfo

func (m *QueryDiscountTokenStatusQResponse) GetDiscountToken() *DiscountToken {
	if m != nil {
		return m.DiscountToken
	}
	return nil
}

func (m *QueryDiscountTokenStatusQResponse) GetDiscountTokenStatus() []*DiscountTokenStatus {
	if m != nil {
		return m.DiscountTokenStatus
	}
	return nil
}

func (m *QueryDiscountTokenStatusQResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryMembershipTokensRequest struct {
	// Adding pagination to request
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMembershipTokensRequest) Reset()         { *m = QueryMembershipTokensRequest{} }
func (m *QueryMembershipTokensRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMembershipTokensRequest) ProtoMessage()    {}
func (*QueryMembershipTokensRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257a72cb45763f8, []int{10}
}
func (m *QueryMembershipTokensRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMembershipTokensRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMembershipTokensRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMembershipTokensRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMembershipTokensRequest.Merge(m, src)
}
func (m *QueryMembershipTokensRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMembershipTokensRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMembershipTokensRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMembershipTokensRequest proto.InternalMessageInfo

func (m *QueryMembershipTokensRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryMembershipTokensResponse struct {
	// Returning a list of posts
	MembershipToken []*MembershipToken `protobuf:"bytes,1,rep,name=MembershipToken,proto3" json:"MembershipToken,omitempty"`
	// Adding pagination to response
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMembershipTokensResponse) Reset()         { *m = QueryMembershipTokensResponse{} }
func (m *QueryMembershipTokensResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMembershipTokensResponse) ProtoMessage()    {}
func (*QueryMembershipTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9257a72cb45763f8, []int{11}
}
func (m *QueryMembershipTokensResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMembershipTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMembershipTokensResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMembershipTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMembershipTokensResponse.Merge(m, src)
}
func (m *QueryMembershipTokensResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMembershipTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMembershipTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMembershipTokensResponse proto.InternalMessageInfo

func (m *QueryMembershipTokensResponse) GetMembershipToken() []*MembershipToken {
	if m != nil {
		return m.MembershipToken
	}
	return nil
}

func (m *QueryMembershipTokensResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "mitoblockchaindev.mitoblockchaindev.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "mitoblockchaindev.mitoblockchaindev.QueryParamsResponse")
	proto.RegisterType((*QueryDiscountTokensRequest)(nil), "mitoblockchaindev.mitoblockchaindev.QueryDiscountTokensRequest")
	proto.RegisterType((*QueryDiscountTokensResponse)(nil), "mitoblockchaindev.mitoblockchaindev.QueryDiscountTokensResponse")
	proto.RegisterType((*QueryGetDiscountTokenStatusRequest)(nil), "mitoblockchaindev.mitoblockchaindev.QueryGetDiscountTokenStatusRequest")
	proto.RegisterType((*QueryGetDiscountTokenStatusResponse)(nil), "mitoblockchaindev.mitoblockchaindev.QueryGetDiscountTokenStatusResponse")
	proto.RegisterType((*QueryAllDiscountTokenStatusRequest)(nil), "mitoblockchaindev.mitoblockchaindev.QueryAllDiscountTokenStatusRequest")
	proto.RegisterType((*QueryAllDiscountTokenStatusResponse)(nil), "mitoblockchaindev.mitoblockchaindev.QueryAllDiscountTokenStatusResponse")
	proto.RegisterType((*QueryDiscountTokenStatusQRequest)(nil), "mitoblockchaindev.mitoblockchaindev.QueryDiscountTokenStatusQRequest")
	proto.RegisterType((*QueryDiscountTokenStatusQResponse)(nil), "mitoblockchaindev.mitoblockchaindev.QueryDiscountTokenStatusQResponse")
	proto.RegisterType((*QueryMembershipTokensRequest)(nil), "mitoblockchaindev.mitoblockchaindev.QueryMembershipTokensRequest")
	proto.RegisterType((*QueryMembershipTokensResponse)(nil), "mitoblockchaindev.mitoblockchaindev.QueryMembershipTokensResponse")
}

func init() { proto.RegisterFile("mitoblockchaindev/query.proto", fileDescriptor_9257a72cb45763f8) }

var fileDescriptor_9257a72cb45763f8 = []byte{
	// 753 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x97, 0xcf, 0x4f, 0x13, 0x41,
	0x14, 0xc7, 0x3b, 0x0b, 0x72, 0x78, 0x44, 0x34, 0x03, 0x31, 0x64, 0x85, 0x15, 0x97, 0x04, 0x89,
	0x84, 0xdd, 0x50, 0x08, 0x12, 0x43, 0xc4, 0x56, 0x01, 0x39, 0x98, 0x40, 0xf5, 0x60, 0x3c, 0x88,
	0xdb, 0x76, 0x2c, 0x2b, 0xdb, 0x9d, 0xa5, 0xb3, 0x25, 0xa2, 0xf1, 0xe2, 0x5f, 0x60, 0xe2, 0xc1,
	0x7f, 0xc3, 0xf8, 0x17, 0x98, 0x78, 0xe1, 0x88, 0xf1, 0xa2, 0x17, 0x43, 0xc0, 0xbb, 0xfa, 0x1f,
	0x98, 0xce, 0x4c, 0x95, 0xed, 0x6e, 0xcb, 0x76, 0x5b, 0x6e, 0xcd, 0xce, 0xfb, 0xf5, 0xf9, 0xbe,
	0xb7, 0xf3, 0xb6, 0x30, 0x5a, 0xb6, 0x7d, 0x9a, 0x77, 0x68, 0x61, 0xbb, 0xb0, 0x65, 0xd9, 0x6e,
	0x91, 0xec, 0x9a, 0x3b, 0x55, 0x52, 0xd9, 0x33, 0xbc, 0x0a, 0xf5, 0x29, 0x1e, 0x0f, 0x1d, 0x1b,
	0xa1, 0x27, 0xea, 0x50, 0x89, 0x96, 0x28, 0xb7, 0x37, 0x6b, 0xbf, 0x84, 0xab, 0x3a, 0x52, 0xa2,
	0xb4, 0xe4, 0x10, 0xd3, 0xf2, 0x6c, 0xd3, 0x72, 0x5d, 0xea, 0x5b, 0xbe, 0x4d, 0x5d, 0x26, 0x4f,
	0xaf, 0x17, 0x28, 0x2b, 0x53, 0x66, 0xe6, 0x2d, 0x46, 0x44, 0x46, 0x73, 0x77, 0x26, 0x4f, 0x7c,
	0x6b, 0xc6, 0xf4, 0xac, 0x92, 0xed, 0x72, 0x63, 0x69, 0xab, 0x85, 0x6b, 0xf4, 0xac, 0x8a, 0x55,
	0xae, 0xc7, 0x9a, 0x0e, 0x9f, 0x17, 0x6d, 0x56, 0xa0, 0x55, 0xd7, 0xdf, 0xf4, 0xe9, 0x36, 0x71,
	0x37, 0x99, 0x6f, 0xf9, 0xd5, 0xba, 0xf9, 0xc4, 0x69, 0xe6, 0xd2, 0x6e, 0x32, 0x6c, 0x57, 0x26,
	0xe5, 0x3c, 0xa9, 0xb0, 0x2d, 0xdb, 0x3b, 0x69, 0xa9, 0x0f, 0x01, 0xde, 0xa8, 0x21, 0xac, 0xf3,
	0xaa, 0x72, 0x64, 0xa7, 0x4a, 0x98, 0xaf, 0x3f, 0x85, 0xc1, 0xc0, 0x53, 0xe6, 0x51, 0x97, 0x11,
	0xbc, 0x06, 0x7d, 0xa2, 0xfa, 0x61, 0x34, 0x86, 0x26, 0xfb, 0xd3, 0x53, 0x46, 0x0c, 0x8d, 0x0d,
	0x11, 0x24, 0xdb, 0xbb, 0xff, 0xe3, 0x4a, 0x2a, 0x27, 0x03, 0xe8, 0x45, 0x50, 0x79, 0x86, 0xbb,
	0xb2, 0xfc, 0x87, 0xb5, 0x9a, 0xea, 0xf9, 0xf1, 0x0a, 0xc0, 0x7f, 0x29, 0x65, 0xb2, 0x09, 0x43,
	0xe8, 0x6e, 0xd4, 0x74, 0x37, 0x44, 0xa7, 0xa5, 0xee, 0xc6, 0xba, 0x55, 0x22, 0xd2, 0x37, 0x77,
	0xc2, 0x53, 0xff, 0x84, 0xe0, 0x72, 0x64, 0x1a, 0x09, 0xf4, 0x08, 0xce, 0x07, 0x4e, 0x86, 0xd1,
	0x58, 0xcf, 0x64, 0x7f, 0x3a, 0x1d, 0x8b, 0x2b, 0xe0, 0x99, 0x0b, 0x06, 0xc2, 0xab, 0x01, 0x02,
	0x85, 0x13, 0x5c, 0x3b, 0x95, 0x40, 0x94, 0x15, 0x40, 0x98, 0x03, 0x9d, 0x13, 0xac, 0x12, 0x3f,
	0x90, 0xe1, 0x01, 0x9f, 0x8b, 0xba, 0x60, 0x03, 0xa0, 0xd8, 0x45, 0x2e, 0x54, 0x6f, 0x4e, 0xb1,
	0x8b, 0xfa, 0x7b, 0x04, 0xe3, 0x2d, 0xdd, 0xa4, 0x00, 0x1e, 0x0c, 0x46, 0x1c, 0x4b, 0xc5, 0x17,
	0xda, 0x97, 0x41, 0xf8, 0xcb, 0x5e, 0x47, 0x85, 0xd6, 0x1d, 0xc9, 0x93, 0x71, 0x9c, 0x16, 0x3c,
	0xdd, 0x1a, 0x80, 0xc3, 0xba, 0x0e, 0xcd, 0xd2, 0x9d, 0xa6, 0x43, 0xcf, 0x19, 0xe9, 0xd0, 0xbd,
	0x01, 0x79, 0x09, 0x63, 0xe1, 0x11, 0x17, 0x49, 0x36, 0x9a, 0x8c, 0x47, 0x83, 0xbc, 0x4a, 0x62,
	0x79, 0x3f, 0x2a, 0x70, 0xb5, 0x45, 0xf2, 0xe6, 0x6f, 0x19, 0xea, 0xce, 0x5b, 0xf6, 0x3c, 0xba,
	0x6d, 0x4a, 0x67, 0x6d, 0x8b, 0xd3, 0xb0, 0x9e, 0xe4, 0x0d, 0x7b, 0x06, 0x23, 0x5c, 0xb3, 0xfb,
	0xff, 0x6e, 0xe4, 0xb3, 0xb9, 0xfc, 0xf6, 0x11, 0x8c, 0x36, 0x49, 0x24, 0x1b, 0xf3, 0x04, 0x2e,
	0x34, 0x9c, 0xc9, 0x89, 0x9f, 0x8b, 0x25, 0x5d, 0x83, 0x6f, 0xae, 0x31, 0x58, 0xd7, 0x66, 0x3c,
	0xfd, 0x19, 0xe0, 0x1c, 0x47, 0xc1, 0x1f, 0x10, 0xf4, 0x89, 0x85, 0x82, 0x6f, 0xc4, 0x2a, 0x32,
	0xbc, 0xdd, 0xd4, 0x85, 0xf6, 0x1d, 0x45, 0x4d, 0xfa, 0xec, 0x9b, 0xaf, 0x3f, 0xdf, 0x29, 0xd3,
	0x78, 0xca, 0x8c, 0x58, 0xb0, 0x4d, 0x36, 0x3d, 0xfe, 0x82, 0x60, 0x20, 0xb8, 0x7f, 0xf0, 0x52,
	0xfc, 0x0a, 0x22, 0x17, 0xa4, 0x7a, 0x3b, 0x79, 0x00, 0x89, 0xb2, 0xc8, 0x51, 0xe6, 0xf1, 0x5c,
	0x2c, 0x94, 0xe0, 0x57, 0x06, 0xc3, 0x7f, 0x10, 0x44, 0xbf, 0x24, 0xf1, 0xeb, 0x6a, 0xb9, 0xd0,
	0xd4, 0x7b, 0x9d, 0x07, 0x92, 0xa0, 0xab, 0x1c, 0x34, 0x83, 0x97, 0x12, 0x80, 0xca, 0xaf, 0x2f,
	0xf3, 0x95, 0x5d, 0x7c, 0x8d, 0x7f, 0x21, 0xb8, 0x14, 0x91, 0x28, 0xe3, 0x38, 0xed, 0x60, 0xb7,
	0xdc, 0x7b, 0xed, 0x60, 0xb7, 0xde, 0x68, 0x7a, 0x96, 0x63, 0x2f, 0xe2, 0x9b, 0xc9, 0xb1, 0xf1,
	0x6f, 0x04, 0x43, 0x51, 0x37, 0x3b, 0x5e, 0x4e, 0x38, 0x7e, 0xc1, 0xb5, 0xa4, 0xae, 0x74, 0x1a,
	0x46, 0xb2, 0xae, 0x71, 0xd6, 0x3b, 0x38, 0x93, 0x9c, 0x75, 0x73, 0x47, 0x34, 0xf9, 0x3b, 0x82,
	0x8b, 0x8d, 0xf7, 0x25, 0xce, 0xc4, 0xaf, 0xb3, 0xc9, 0xa5, 0xae, 0x66, 0x3b, 0x09, 0x21, 0x31,
	0x6f, 0x71, 0xcc, 0x05, 0x3c, 0x1f, 0x0b, 0xb3, 0xf1, 0x83, 0x9f, 0x65, 0x97, 0xf7, 0x8f, 0x34,
	0x74, 0x70, 0xa4, 0xa1, 0xc3, 0x23, 0x0d, 0xbd, 0x3d, 0xd6, 0x52, 0x07, 0xc7, 0x5a, 0xea, 0xdb,
	0xb1, 0x96, 0x7a, 0x3c, 0x15, 0x76, 0x7f, 0x11, 0x11, 0xd2, 0xdf, 0xf3, 0x08, 0xcb, 0xf7, 0xf1,
	0x7f, 0x0e, 0xb3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x54, 0x2c, 0x3b, 0x0d, 0x80, 0x0d, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of DiscountTokens items.
	DiscountTokens(ctx context.Context, in *QueryDiscountTokensRequest, opts ...grpc.CallOption) (*QueryDiscountTokensResponse, error)
	// Queries a DiscountTokenStatus by id.
	DiscountTokenStatus(ctx context.Context, in *QueryGetDiscountTokenStatusRequest, opts ...grpc.CallOption) (*QueryGetDiscountTokenStatusResponse, error)
	// Queries a list of DiscountTokenStatus items.
	DiscountTokenStatusAll(ctx context.Context, in *QueryAllDiscountTokenStatusRequest, opts ...grpc.CallOption) (*QueryAllDiscountTokenStatusResponse, error)
	// Queries a list of DiscountTokenStatusQ items.
	DiscountTokenStatusQ(ctx context.Context, in *QueryDiscountTokenStatusQRequest, opts ...grpc.CallOption) (*QueryDiscountTokenStatusQResponse, error)
	// Queries a list of MembershipTokens items.
	MembershipTokens(ctx context.Context, in *QueryMembershipTokensRequest, opts ...grpc.CallOption) (*QueryMembershipTokensResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/mitoblockchaindev.mitoblockchaindev.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DiscountTokens(ctx context.Context, in *QueryDiscountTokensRequest, opts ...grpc.CallOption) (*QueryDiscountTokensResponse, error) {
	out := new(QueryDiscountTokensResponse)
	err := c.cc.Invoke(ctx, "/mitoblockchaindev.mitoblockchaindev.Query/DiscountTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DiscountTokenStatus(ctx context.Context, in *QueryGetDiscountTokenStatusRequest, opts ...grpc.CallOption) (*QueryGetDiscountTokenStatusResponse, error) {
	out := new(QueryGetDiscountTokenStatusResponse)
	err := c.cc.Invoke(ctx, "/mitoblockchaindev.mitoblockchaindev.Query/DiscountTokenStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DiscountTokenStatusAll(ctx context.Context, in *QueryAllDiscountTokenStatusRequest, opts ...grpc.CallOption) (*QueryAllDiscountTokenStatusResponse, error) {
	out := new(QueryAllDiscountTokenStatusResponse)
	err := c.cc.Invoke(ctx, "/mitoblockchaindev.mitoblockchaindev.Query/DiscountTokenStatusAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DiscountTokenStatusQ(ctx context.Context, in *QueryDiscountTokenStatusQRequest, opts ...grpc.CallOption) (*QueryDiscountTokenStatusQResponse, error) {
	out := new(QueryDiscountTokenStatusQResponse)
	err := c.cc.Invoke(ctx, "/mitoblockchaindev.mitoblockchaindev.Query/DiscountTokenStatusQ", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MembershipTokens(ctx context.Context, in *QueryMembershipTokensRequest, opts ...grpc.CallOption) (*QueryMembershipTokensResponse, error) {
	out := new(QueryMembershipTokensResponse)
	err := c.cc.Invoke(ctx, "/mitoblockchaindev.mitoblockchaindev.Query/MembershipTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of DiscountTokens items.
	DiscountTokens(context.Context, *QueryDiscountTokensRequest) (*QueryDiscountTokensResponse, error)
	// Queries a DiscountTokenStatus by id.
	DiscountTokenStatus(context.Context, *QueryGetDiscountTokenStatusRequest) (*QueryGetDiscountTokenStatusResponse, error)
	// Queries a list of DiscountTokenStatus items.
	DiscountTokenStatusAll(context.Context, *QueryAllDiscountTokenStatusRequest) (*QueryAllDiscountTokenStatusResponse, error)
	// Queries a list of DiscountTokenStatusQ items.
	DiscountTokenStatusQ(context.Context, *QueryDiscountTokenStatusQRequest) (*QueryDiscountTokenStatusQResponse, error)
	// Queries a list of MembershipTokens items.
	MembershipTokens(context.Context, *QueryMembershipTokensRequest) (*QueryMembershipTokensResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) DiscountTokens(ctx context.Context, req *QueryDiscountTokensRequest) (*QueryDiscountTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscountTokens not implemented")
}
func (*UnimplementedQueryServer) DiscountTokenStatus(ctx context.Context, req *QueryGetDiscountTokenStatusRequest) (*QueryGetDiscountTokenStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscountTokenStatus not implemented")
}
func (*UnimplementedQueryServer) DiscountTokenStatusAll(ctx context.Context, req *QueryAllDiscountTokenStatusRequest) (*QueryAllDiscountTokenStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscountTokenStatusAll not implemented")
}
func (*UnimplementedQueryServer) DiscountTokenStatusQ(ctx context.Context, req *QueryDiscountTokenStatusQRequest) (*QueryDiscountTokenStatusQResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscountTokenStatusQ not implemented")
}
func (*UnimplementedQueryServer) MembershipTokens(ctx context.Context, req *QueryMembershipTokensRequest) (*QueryMembershipTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MembershipTokens not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mitoblockchaindev.mitoblockchaindev.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DiscountTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDiscountTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DiscountTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mitoblockchaindev.mitoblockchaindev.Query/DiscountTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DiscountTokens(ctx, req.(*QueryDiscountTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DiscountTokenStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDiscountTokenStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DiscountTokenStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mitoblockchaindev.mitoblockchaindev.Query/DiscountTokenStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DiscountTokenStatus(ctx, req.(*QueryGetDiscountTokenStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DiscountTokenStatusAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDiscountTokenStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DiscountTokenStatusAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mitoblockchaindev.mitoblockchaindev.Query/DiscountTokenStatusAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DiscountTokenStatusAll(ctx, req.(*QueryAllDiscountTokenStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DiscountTokenStatusQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDiscountTokenStatusQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DiscountTokenStatusQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mitoblockchaindev.mitoblockchaindev.Query/DiscountTokenStatusQ",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DiscountTokenStatusQ(ctx, req.(*QueryDiscountTokenStatusQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MembershipTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMembershipTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MembershipTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mitoblockchaindev.mitoblockchaindev.Query/MembershipTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MembershipTokens(ctx, req.(*QueryMembershipTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mitoblockchaindev.mitoblockchaindev.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "DiscountTokens",
			Handler:    _Query_DiscountTokens_Handler,
		},
		{
			MethodName: "DiscountTokenStatus",
			Handler:    _Query_DiscountTokenStatus_Handler,
		},
		{
			MethodName: "DiscountTokenStatusAll",
			Handler:    _Query_DiscountTokenStatusAll_Handler,
		},
		{
			MethodName: "DiscountTokenStatusQ",
			Handler:    _Query_DiscountTokenStatusQ_Handler,
		},
		{
			MethodName: "MembershipTokens",
			Handler:    _Query_MembershipTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mitoblockchaindev/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryDiscountTokensRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDiscountTokensRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDiscountTokensRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDiscountTokensResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDiscountTokensResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDiscountTokensResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.DiscountToken) > 0 {
		for iNdEx := len(m.DiscountToken) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DiscountToken[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDiscountTokenStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDiscountTokenStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDiscountTokenStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDiscountTokenStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDiscountTokenStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDiscountTokenStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.DiscountTokenStatus.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllDiscountTokenStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDiscountTokenStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDiscountTokenStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDiscountTokenStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDiscountTokenStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDiscountTokenStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.DiscountTokenStatus) > 0 {
		for iNdEx := len(m.DiscountTokenStatus) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DiscountTokenStatus[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryDiscountTokenStatusQRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDiscountTokenStatusQRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDiscountTokenStatusQRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryDiscountTokenStatusQResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDiscountTokenStatusQResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDiscountTokenStatusQResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DiscountTokenStatus) > 0 {
		for iNdEx := len(m.DiscountTokenStatus) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DiscountTokenStatus[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.DiscountToken != nil {
		{
			size, err := m.DiscountToken.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMembershipTokensRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMembershipTokensRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMembershipTokensRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMembershipTokensResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMembershipTokensResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMembershipTokensResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.MembershipToken) > 0 {
		for iNdEx := len(m.MembershipToken) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MembershipToken[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryDiscountTokensRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDiscountTokensResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DiscountToken) > 0 {
		for _, e := range m.DiscountToken {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDiscountTokenStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetDiscountTokenStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DiscountTokenStatus.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllDiscountTokenStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDiscountTokenStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DiscountTokenStatus) > 0 {
		for _, e := range m.DiscountTokenStatus {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDiscountTokenStatusQRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDiscountTokenStatusQResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DiscountToken != nil {
		l = m.DiscountToken.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.DiscountTokenStatus) > 0 {
		for _, e := range m.DiscountTokenStatus {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMembershipTokensRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMembershipTokensResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MembershipToken) > 0 {
		for _, e := range m.MembershipToken {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDiscountTokensRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDiscountTokensRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDiscountTokensRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDiscountTokensResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDiscountTokensResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDiscountTokensResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiscountToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DiscountToken = append(m.DiscountToken, &DiscountToken{})
			if err := m.DiscountToken[len(m.DiscountToken)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDiscountTokenStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDiscountTokenStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDiscountTokenStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDiscountTokenStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDiscountTokenStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDiscountTokenStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiscountTokenStatus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DiscountTokenStatus.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDiscountTokenStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDiscountTokenStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDiscountTokenStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDiscountTokenStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDiscountTokenStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDiscountTokenStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiscountTokenStatus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DiscountTokenStatus = append(m.DiscountTokenStatus, DiscountTokenStatus{})
			if err := m.DiscountTokenStatus[len(m.DiscountTokenStatus)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDiscountTokenStatusQRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDiscountTokenStatusQRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDiscountTokenStatusQRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDiscountTokenStatusQResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDiscountTokenStatusQResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDiscountTokenStatusQResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiscountToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DiscountToken == nil {
				m.DiscountToken = &DiscountToken{}
			}
			if err := m.DiscountToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiscountTokenStatus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DiscountTokenStatus = append(m.DiscountTokenStatus, &DiscountTokenStatus{})
			if err := m.DiscountTokenStatus[len(m.DiscountTokenStatus)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMembershipTokensRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMembershipTokensRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMembershipTokensRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMembershipTokensResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMembershipTokensResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMembershipTokensResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MembershipToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MembershipToken = append(m.MembershipToken, &MembershipToken{})
			if err := m.MembershipToken[len(m.MembershipToken)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
